export const queryKeys = {
  me: ['me'] as const,
  csrf: ['csrf'] as const,
  dashboard: (perfil: string) => ['dashboard', perfil] as const,
  dataExport: (jobId: string) => ['me', 'data-export', jobId] as const,
  contato: ['publico', 'contato'] as const,
  protocolo: (ano: string, numero: string) => ['publico', 'protocolo', ano, numero] as const,
  certificado: (hash: string) => ['publico', 'certificado', hash] as const,
  jwks: ['jwks'] as const,
  requestTypes: ['requests', 'types'] as const,
  requestType: (code: string) => ['requests', 'types', code] as const,
  requests: (filters: Record<string, string | number | undefined>) =>
    ['requests', 'list', filters] as const,
  request: (id: string) => ['requests', 'detail', id] as const,
  requestEvents: (id: string) => ['requests', 'events', id] as const,
  requestAttachments: (id: string) => ['requests', 'attachments', id] as const,
  requestProtocol: (id: string) => ['requests', 'protocol', id] as const,
  cursos: ['academico', 'cursos'] as const,
  disciplinas: (q: Record<string, string | undefined>) => ['academico', 'disciplinas', q] as const,
  formativas: (page?: number) => ['formativas', 'minhas', page ?? 0] as const,
  formativasResumo: ['formativas', 'resumo'] as const,
  eventos: (q: Record<string, string | number | undefined>) => ['events', 'list', q] as const,
  evento: (id: string) => ['events', 'detail', id] as const,
  eventoSessao: (id: string) => ['events', 'session', id] as const,
  certificados: ['certificates', 'mine'] as const,
  atendimentos: (status?: string) => ['service-records', 'me', status ?? ''] as const,
  inbox: (page?: number) => ['communications', 'me', page ?? 0] as const,
  inboxUnread: ['communications', 'unread'] as const,
  faq: (categoria?: string) => ['faq', categoria ?? ''] as const,
  ticketsMine: ['support', 'tickets', 'mine'] as const,
  internshipsMine: (page?: number) => ['internships', 'mine', page ?? 0] as const,
  internship: (id: string) => ['internships', 'detail', id] as const,
  internshipDocs: (id: string) => ['internships', 'documents', id] as const,
  tccsMine: ['tccs', 'mine'] as const,
  tccsList: (estado?: string) => ['tccs', 'list', estado ?? ''] as const,
  tcc: (id: string) => ['tccs', 'detail', id] as const,
  diplomaUrl: (id: string) => ['graduations', 'diploma-url', id] as const,
  eventosHost: (q?: Record<string, string | number | undefined>) =>
    ['events', 'host', q ?? {}] as const,
  caafPool: (page?: number) => ['commissions', 'caaf', 'pool', page ?? 0] as const,
  caafStats: ['commissions', 'caaf', 'stats'] as const,
  coePool: (page?: number) => ['commissions', 'coe', 'pool', page ?? 0] as const,
  coeStats: ['commissions', 'coe', 'stats'] as const,
  usuarios: (q: Record<string, string | number | undefined>) => ['usuarios', 'list', q] as const,
  usuario: (id: string) => ['usuarios', 'detail', id] as const,
  tasks: (estado?: string) => ['tasks', estado ?? ''] as const,
  reports: (kind: string, q: Record<string, string | undefined>) => ['reports', kind, q] as const,
  courseConfig: (id: string) => ['courses', 'config', id] as const,
  adminRequestTypes: ['request-types'] as const,
  adminRoles: ['admin', 'roles'] as const,
  adminAuthorities: ['admin', 'autoridades'] as const,
  search: (q: Record<string, string | number | undefined>) => ['search', q] as const,
  importJob: (id: string) => ['imports', id] as const,
  exportJob: (id: string) => ['exports', 'job', id] as const,
  exportsList: ['exports', 'list'] as const,
  outbox: (status: string, page?: number) => ['admin', 'outbox', status, page ?? 0] as const,
  graduations: (estado?: string) => ['graduations', 'list', estado ?? ''] as const,
  studentsElig: (eligible?: string) => ['students', 'elig', eligible ?? ''] as const,
  templates: ['communication-templates'] as const,
  templateVersions: (id: string) => ['communication-templates', 'versions', id] as const,
  audit: (q: Record<string, string | number | undefined>) => ['admin', 'audit', q] as const,
  ticketsStaff: (estado?: string) => ['support', 'tickets', 'staff', estado ?? ''] as const,
  disciplinasLookup: (q: Record<string, string | undefined>) => ['academico', 'disciplinas', 'lookup', q] as const,
}
